### NUMPY: Arrays and Matrices

In [2]:
import numpy as np

### Create arrays

In [3]:
# create ndarrays from lists
# note: every element must be the same data type (will be converted is possible)
data1 = [1, 2, 3, 4, 5]        # list
arr1 = np.array(data1)         # 1-D array
print (data1, type(data1))
print (arr1, type(arr1))

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


In [4]:
data2 = [range(1, 5), range(5, 9)]    # list of lists
arr2 = np.array(data2)                # 2-D array
print (data2, type(data2))
print (arr2, type(arr2))

[range(1, 5), range(5, 9)] <class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [5]:
list2 = arr2.tolist()                  # converting ndarray back to a list
print (list2, type(list2))

[[1, 2, 3, 4], [5, 6, 7, 8]] <class 'list'>


In [6]:
print (list(range(1, 5)))

[1, 2, 3, 4]


In [7]:
# examining arrays
print (arr1, type(arr1), id(arr1))
print (arr2, type(arr2), id(arr2))
print (arr1.dtype)        # data type of the array
print (arr2.dtype)
print (arr1.shape, type(arr1.shape))        # shape of the array (5,) => Singleton notation
print (arr2.shape, type(arr2.shape))        # shape of the array (2, 4)
print (arr1.ndim)        # number of dimensions
print (arr2.ndim)
print (arr1.size)        # total number of elements
print (arr2.size)
print (len(arr1))        # size of the first dimension (aka axis)
print (len(arr2))

[1 2 3 4 5] <class 'numpy.ndarray'> 2858335286736
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> 2858340274304
int32
int32
(5,) <class 'tuple'>
(2, 4) <class 'tuple'>
1
2
5
8
5
2


In [8]:
data3 = [range(1, 6), range(5, 10)]    # list of lists
arr3 = np.array(data3)                 # 2-D array
print (data3, type(data3))
print (arr3, type(arr3))

[range(1, 6), range(5, 10)] <class 'list'>
[[1 2 3 4 5]
 [5 6 7 8 9]] <class 'numpy.ndarray'>


In [9]:
# create special arrays
print (np.zeros(10))
print (np.zeros((3, 6)))
print (np.ones(10))
print (np.ones((3, 6)))
print (np.linspace(0, 1, 5))  # 0 to 1 (inclusive) with 5 points  #Equi Distance Values
print (np.logspace(0, 3, 4))  # 10^0 to 10^3 (inclusive) with 4 points

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]
[0.   0.25 0.5  0.75 1.  ]
[   1.   10.  100. 1000.]


In [10]:
list1 = [10, 20, 30, 40, 50]
print (list1, type(list1))
arr1 = np.array(list1)
print (arr1)
print (arr1.dtype)

[10, 20, 30, 40, 50] <class 'list'>
[10 20 30 40 50]
int32


In [11]:
list1 = [10, 20, '30', 40, 50]
print (list1, type(list1))
arr1 = np.array(list1)
print (arr1)
print (arr1.dtype)

[10, 20, '30', 40, 50] <class 'list'>
['10' '20' '30' '40' '50']
<U11


In [12]:
# arange is like rage, except it returns an array (but not a list)
int_list = list(range(5))
print (int_list, type(int_list[0]), type(int_list))
int_array = np.arange(5)
print (int_array, int_array.dtype, type(int_array))
float_array = int_array.astype(float)
print (float_array, float_array.dtype, type(float_array))

[0, 1, 2, 3, 4] <class 'int'> <class 'list'>
[0 1 2 3 4] int32 <class 'numpy.ndarray'>
[0. 1. 2. 3. 4.] float64 <class 'numpy.ndarray'>


### Reshaping

In [4]:
matrix = np.arange(10, dtype=float)
print (matrix, matrix.dtype, type(matrix), matrix.shape)
matrix = matrix.reshape((2, 5))
print (matrix, matrix.dtype, type(matrix), matrix.shape)
# transpose of a matrix
matrix = matrix.T
print (matrix, matrix.dtype, type(matrix), matrix.shape)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.] float64 <class 'numpy.ndarray'> (10,)
[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]] float64 <class 'numpy.ndarray'> (2, 5)
[[0. 5.]
 [1. 6.]
 [2. 7.]
 [3. 8.]
 [4. 9.]] float64 <class 'numpy.ndarray'> (5, 2)


### Selection

In [55]:
data1 = [1, 2, 3, 4, 5]        # list
arr1 = np.array(data1)         # 1-D array
print (arr1, type(arr1), arr1.dtype, arr1.shape)
print (arr1[0], arr1[-5])      # 0th element (indexing like a list)
print (arr1[4], arr1[-1])
print (arr1[2:], arr1[:3])
print (arr1[::-1])

[1 2 3 4 5] <class 'numpy.ndarray'> int32 (5,)
1 1
5 5
[3 4 5] [1 2 3]
[5 4 3 2 1]


In [62]:
data2 = [range(1, 5), range(5, 9)]    # list of lists
arr2 = np.array(data2)                # 2-D array
print (arr2, type(arr2), arr2.dtype, arr2.shape)
print (arr2[1][2])                    # indexing
print (arr2[0, :], arr2[1, :])        # slicing
print (arr2[:, 2])
print (arr2[:, 1:4])                  # all rows and columns from 1 (inclusive) to 4 (exclusive)

[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'> int32 (2, 4)
7
[1 2 3 4] [5 6 7 8]
[3 7]
[[2 3 4]
 [6 7 8]]


### Views and copies

In [70]:
arr = np.arange(10)
print (arr, type(arr), arr.dtype, arr.shape)
print (arr[5:8])
arr[5:8] = 12       # all the pre-existing values at those index places will be over-written
print (arr)
arr_view = arr[5:8]   # creates a view of arr, not a copy
print (arr_view, type(arr_view), arr_view.dtype, arr_view.shape)
arr_view[:] = 13
print (arr_view)
print (arr)
arr_copy = arr[5:8].copy()   # creates a copy of arr
print (arr_copy, type(arr_copy), arr_copy.dtype, arr_copy.shape)
arr_copy[:] = 14
print (arr_copy)
print (arr)

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'> int32 (10,)
[5 6 7]
[ 0  1  2  3  4 12 12 12  8  9]
[12 12 12] <class 'numpy.ndarray'> int32 (3,)
[13 13 13]
[ 0  1  2  3  4 13 13 13  8  9]
[13 13 13] <class 'numpy.ndarray'> int32 (3,)
[14 14 14]
[ 0  1  2  3  4 13 13 13  8  9]


In [77]:
list1 = [11, 22, 33, 44]
print (list1)
list2 = list1
print (list2)
print (id(list1), id(list2))
list1[0] = 100
print (list1, list2)
list3 = []
list3[:] = list1
print (list3)
print (id(list1), id(list3))
list1[0] = 500
print (list1, list3)

[11, 22, 33, 44]
[11, 22, 33, 44]
611704500168 611704500168
[100, 22, 33, 44] [100, 22, 33, 44]
[100, 22, 33, 44]
611704500168 611703970824
[500, 22, 33, 44] [100, 22, 33, 44]


### Using boolean arrays

In [82]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print (arr)
print (arr > 5)
print (arr[arr > 5])
print (arr % 2 == 0)
print (arr[arr % 2 == 0])

[1 2 3 4 5 6 7 8 9]
[False False False False False  True  True  True  True]
[6 7 8 9]
[False  True False  True False  True False  True False]
[2 4 6 8]


In [89]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print (names)
print (names == 'Bob')
print (names[names == 'Bob'])
print (names[names != 'Bob'])
print (names[(names == 'Bob') | (names == 'Will')])  # don't use or but use |
names[names != 'Bob'] = 'Tom'   # assign based on a logical selection
print (names)
print (np.unique(names))        # getting all unique names

['Bob' 'Joe' 'Will' 'Bob']
[ True False False  True]
['Bob' 'Bob']
['Joe' 'Will']
['Bob' 'Will' 'Bob']
['Bob' 'Tom' 'Tom' 'Bob']
['Bob' 'Tom']


### Vectorized operations

In [98]:
nums = np.arange(5)
print (nums)
print (nums * 5)
nums = np.sqrt(nums)
print (nums)
print (np.ceil(nums))
print (np.floor(nums))
print (np.isnan(nums))
nums = np.arange(5)
print (nums + np.arange(5))

[0 1 2 3 4]
[ 0  5 10 15 20]
[0.         1.         1.41421356 1.73205081 2.        ]
[0. 1. 2. 2. 2.]
[0. 1. 1. 1. 2.]
[False False False False False]
[0 2 4 6 8]


In [101]:
nums = np.arange(5)
print (nums)
print (np.maximum(nums, np.array([10, -2, 13, -4, 5])))

[0 1 2 3 4]
[10  1 13  3  5]


In [109]:
# calculating Euclidean distance between 2 vectors
vec1 = np.random.randn(10)
print (vec1)
vec2 = np.random.randn(10)
print (vec2)
dist = np.sqrt(np.sum((vec1 - vec2) ** 2))
print (dist)

[-0.41563512  0.48324439  0.38733903  1.30322412  1.7371045   0.78690694
  1.22861502  0.93561371  3.03578433  1.24001407]
[ 0.50141317  0.7110653   0.69320512  1.52759572  0.27565787  1.6130179
  0.26594882  0.1769295  -0.20513815  0.51426863]
4.048169356418958


In [110]:
vec1 = np.random.rand(10)
print (vec1)

[0.72579487 0.26012751 0.00965647 0.23520843 0.44760095 0.83032984
 0.80130634 0.0618527  0.5695175  0.64239164]


In [117]:
# math and stats
rnd = np.random.randn(4, 2)
print (rnd)
print (rnd.mean())
print (rnd.std())
print (rnd.argmin())        # index of the minimum element
print (rnd.sum(axis = 0))   # sum of columns
print (rnd.sum(axis = 1))   # sum of rows

[[-0.09504393  0.74078607]
 [-1.13961014  0.24753756]
 [-1.4473362  -0.64888177]
 [ 0.08831257  1.75668749]]
-0.062193542121831036
0.9680146468224654
4
[-2.59367769  2.09612936]
[ 0.64574214 -0.89207258 -2.09621797  1.84500007]


In [144]:
# methods for boolean arrays
rnd = np.random.randn(4, 2)
print (rnd)
print ((rnd > 0).sum())      # counts the number of positive values
print ((rnd > 0).any())      # checks if any value is True
print ((rnd > 0).all())      # checks if all values are True

[[-1.07474258 -0.08614349]
 [ 1.17583854 -1.63509173]
 [ 1.228194    1.07638625]
 [ 0.39477287 -0.38770082]]
4
True
False


In [126]:
# reshape, transpose, flatten
nums = np.arange(32)
print (nums)
nums = nums.reshape(8, 4)    # creates 8 x 4 matrix
print (nums)
nums = nums.T
print (nums)
nums = nums.flatten()        # flatten
print (nums)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]
[ 0  4  8 12 16 20 24 28  1  5  9 13 17 21 25 29  2  6 10 14 18 22 26 30
  3  7 11 15 19 23 27 31]


In [158]:
# random numbers
np.random.seed(1001)            # set the seed value for the random number generation
nums = np.random.rand(2, 3)     # 2 x 3 matrix
print (nums)
nums = np.random.randn(10)      # random normals (mean with 0 and std with 1)
print (nums)
nums = np.random.randint(0, 2, 10)    # 10 randomly picked 0 or 1
print (nums)

[[0.30623218 0.26506357 0.19606006]
 [0.43052148 0.02311355 0.19578192]]
[-1.20658558 -0.64172681  1.30794563  1.84546043  0.82911495 -0.02329881
 -0.20856395 -0.91661975 -1.07474258 -0.08614349]
[0 0 1 1 1 0 0 0 1 0]


In [145]:
nums = np.random.rand(2, 3)     # 2 x 3 matrix
print (nums)

[[0.24618777 0.60419569 0.81851206]
 [0.41774645 0.06146904 0.90725405]]


### Broadcasting

#### Rules

In [166]:
a = np.array([[ 0,  0,  0],
             [10, 10, 10],
             [20, 20, 20],
             [30, 30, 30]])
print (a, type(a))
b = np.array([0, 1, 2])
print (b, type(b))
result = a + b
print (result)
a = np.array([[0], [10], [20], [30]])
print (a, type(a))
result = a + b
print (result)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] <class 'numpy.ndarray'>
[0 1 2] <class 'numpy.ndarray'>
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
[[ 0]
 [10]
 [20]
 [30]] <class 'numpy.ndarray'>
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]
